package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

var sddCmd = &cobra.Command{
	Use:   "sdd",
	Short: "Spec-Driven Development commands",
	Long:  `SDD (Spec-Driven Development) workflow commands for autonomous feature development.`,
	Run: func(cmd *cobra.Command, args []string) {
		_ = cmd.Help()
	},
}

var sddProposeCmd = &cobra.Command{
	Use:   "propose",
	Short: "Create SDD change proposal",
	RunE: func(cmd *cobra.Command, args []string) error {
		issueNum, _ := cmd.Flags().GetInt("issue")
		title, _ := cmd.Flags().GetString("title")
		body, _ := cmd.Flags().GetString("body")

		if issueNum == 0 {
			return fmt.Errorf("--issue is required")
		}

		proposalDir := filepath.Join(".atl", "proposals")
		if err := os.MkdirAll(proposalDir, 0755); err != nil {
			return err
		}

		path := filepath.Join(proposalDir, fmt.Sprintf("%d.md", issueNum))
		content := fmt.Sprintf(`# SDD Proposal: %s

**Issue**: #%d

%s

---
*Generated by ayrton sdd propose*
`, title, issueNum, body)

		return os.WriteFile(path, []byte(content), 0644)
	},
}

var sddSpecCmd = &cobra.Command{
	Use:   "spec",
	Short: "Write SDD delta specifications",
	RunE: func(cmd *cobra.Command, args []string) error {
		issueNum, _ := cmd.Flags().GetInt("issue")

		if issueNum == 0 {
			return fmt.Errorf("--issue is required")
		}

		specDir := filepath.Join(".atl", "specs")
		if err := os.MkdirAll(specDir, 0755); err != nil {
			return err
		}

		path := filepath.Join(specDir, fmt.Sprintf("%d.md", issueNum))
		content := fmt.Sprintf(`# SDD Spec: Issue #%d

**Issue**: #%d

## Requirements
- [ ] Requirement 1
- [ ] Requirement 2

## Scenarios
- [ ] Scenario 1
- [ ] Scenario 2

## Acceptance Criteria
- [ ] Criterion 1

---
*Generated by ayrton sdd spec*
`, issueNum, issueNum)

		return os.WriteFile(path, []byte(content), 0644)
	},
}

var sddDesignCmd = &cobra.Command{
	Use:   "design",
	Short: "Create technical design document",
	RunE: func(cmd *cobra.Command, args []string) error {
		issueNum, _ := cmd.Flags().GetInt("issue")

		if issueNum == 0 {
			return fmt.Errorf("--issue is required")
		}

		designDir := filepath.Join(".atl", "designs")
		if err := os.MkdirAll(designDir, 0755); err != nil {
			return err
		}

		path := filepath.Join(designDir, fmt.Sprintf("%d.md", issueNum))
		content := fmt.Sprintf(`# SDD Design: Issue #%d

**Issue**: #%d

## Architecture Overview
- TBD

## Components
- Component 1: TBD
- Component 2: TBD

## Data Flow
- TBD

## API Contracts
- TBD

## Security Considerations
- TBD

## Testing Strategy
- Unit tests
- Integration tests

---
*Generated by ayrton sdd design*
`, issueNum, issueNum)

		return os.WriteFile(path, []byte(content), 0644)
	},
}

var sddTasksCmd = &cobra.Command{
	Use:   "tasks",
	Short: "Break change into implementation tasks",
	RunE: func(cmd *cobra.Command, args []string) error {
		issueNum, _ := cmd.Flags().GetInt("issue")

		if issueNum == 0 {
			return fmt.Errorf("--issue is required")
		}

		tasksDir := filepath.Join(".atl", "tasks")
		if err := os.MkdirAll(tasksDir, 0755); err != nil {
			return err
		}

		path := filepath.Join(tasksDir, fmt.Sprintf("%d.md", issueNum))
		content := fmt.Sprintf(`# SDD Tasks: Issue #%d

**Issue**: #%d

## Implementation Tasks
- [ ] Task 1: Setup/preparation
- [ ] Task 2: Core implementation
- [ ] Task 3: Tests
- [ ] Task 4: Documentation
- [ ] Task 5: Code review

## Dependencies
- None

## Estimated Effort
- TBD

---
*Generated by ayrton sdd tasks*
`, issueNum, issueNum)

		return os.WriteFile(path, []byte(content), 0644)
	},
}

var sddApplyCmd = &cobra.Command{
	Use:   "apply",
	Short: "Implement SDD tasks (requires AI agent)",
	RunE: func(cmd *cobra.Command, args []string) error {
		issueNum, _ := cmd.Flags().GetInt("issue")

		if issueNum == 0 {
			return fmt.Errorf("--issue is required")
		}

		fmt.Fprintf(os.Stderr, "⚠️  SDD apply phase requires an AI coding agent\n")
		fmt.Fprintf(os.Stderr, "   This CLI provides the structure; implementation needs an AI agent\n")
		fmt.Fprintf(os.Stderr, "   See .atl/tasks/%d.md for the task list\n", issueNum)
		fmt.Fprintf(os.Stderr, "\n")
		fmt.Fprintf(os.Stderr, "To implement with an AI agent:\n")
		fmt.Fprintf(os.Stderr, "  1. Read the spec: .atl/specs/%d.md\n", issueNum)
		fmt.Fprintf(os.Stderr, "  2. Read the design: .atl/designs/%d.md\n", issueNum)
		fmt.Fprintf(os.Stderr, "  3. Follow tasks: .atl/tasks/%d.md\n", issueNum)
		fmt.Fprintf(os.Stderr, "  4. Implement each task\n")
		fmt.Fprintf(os.Stderr, "  5. Run: ayrton sdd verify --issue %d\n", issueNum)

		return nil
	},
}

var sddVerifyCmd = &cobra.Command{
	Use:   "verify",
	Short: "Run tests and verify implementation",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("Running Go tests...")
		// In real implementation, this would run the test suite
		// For now, just print the command that would run
		fmt.Println("  go test -v -race ./...")
		fmt.Println("  go build ./...")
		fmt.Println("  golangci-lint run")
		fmt.Println("\n✅ Verification phase complete (placeholder)")
		return nil
	},
}

var sddArchiveCmd = &cobra.Command{
	Use:   "archive",
	Short: "Archive completed SDD change",
	RunE: func(cmd *cobra.Command, args []string) error {
		issueNum, _ := cmd.Flags().GetInt("issue")

		if issueNum == 0 {
			return fmt.Errorf("--issue is required")
		}

		fmt.Fprintf(os.Stderr, "Archiving SDD change for issue #%d...\n", issueNum)
		fmt.Fprintf(os.Stderr, "  - Syncing delta specs to main branch\n")
		fmt.Fprintf(os.Stderr, "  - Cleaning up temporary files\n")
		fmt.Fprintf(os.Stderr, "  - Updating project documentation\n")
		fmt.Fprintf(os.Stderr, "\n✅ Archive phase complete (placeholder)\n")

		return nil
	},
}

func init() {
	sddProposeCmd.Flags().Int("issue", 0, "GitHub issue number")
	sddProposeCmd.Flags().String("title", "", "Issue title")
	sddProposeCmd.Flags().String("body", "", "Issue body")
	_ = sddProposeCmd.MarkFlagRequired("issue")

	sddSpecCmd.Flags().Int("issue", 0, "GitHub issue number")
	_ = sddSpecCmd.MarkFlagRequired("issue")

	sddDesignCmd.Flags().Int("issue", 0, "GitHub issue number")
	_ = sddDesignCmd.MarkFlagRequired("issue")

	sddTasksCmd.Flags().Int("issue", 0, "GitHub issue number")
	_ = sddTasksCmd.MarkFlagRequired("issue")

	sddApplyCmd.Flags().Int("issue", 0, "GitHub issue number")
	_ = sddApplyCmd.MarkFlagRequired("issue")

	sddVerifyCmd.Flags().Int("issue", 0, "GitHub issue number")
	_ = sddVerifyCmd.MarkFlagRequired("issue")

	sddArchiveCmd.Flags().Int("issue", 0, "GitHub issue number")
	_ = sddArchiveCmd.MarkFlagRequired("issue")

	sddCmd.AddCommand(
		sddProposeCmd,
		sddSpecCmd,
		sddDesignCmd,
		sddTasksCmd,
		sddApplyCmd,
		sddVerifyCmd,
		sddArchiveCmd,
	)

	rootCmd.AddCommand(sddCmd)
}